### ISSUE TITLE
No response after clicking the layouts button of FancyZone 

### ISSUE THREAD

**Issue by Hwenshuo** [domferr/Linux-PowerToys#12]
No response after clicking the layouts button of FancyZone
The terminal output errors: 
huangwenshuo@pop-os:~/Applications$ ./LinuxPowerToys-0.8-x86_64_f8aecf62cd3ce036b3402fca12b8111c.AppImage 
Gtk-Message: 11:03:07.598: Failed to load module "appmenu-gtk-module"
Gtk-Message: 11:03:07.675: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:03:07.675: Failed to load module "canberra-gtk-module"

** (linuxpowertoys:48504): CRITICAL **: 11:03:08.273: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: 未找到请求的设置

** (linuxpowertoys:48504): CRITICAL **: 11:03:08.276: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: 未找到请求的设置
^C

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.gnome.Shell.Extensions.TilingShell” on object at path /org/gnome/shell/extensions/TilingShell
#0      DBusClient._callMethod (package:dbus/src/dbus_client.dart:1126)
<asynchronous suspension>
#1      DBusClient.callMethod (package:dbus/src/dbus_client.dart:621)
<asynchronous suspension>
#2      GnomeFancyZonesBackend._openLayoutEditor (package:linuxpowertoys/src/backend_api/utilities/fancy_zones/gnome_fancy_zones_backend.dart:320)
<asynchronous suspension>

**Comment by domferr** [comment]
Hello, thank you for opening this issue. Can you share if the issue is still there with the newest version (v0.9)? Thank you
