### ISSUE TITLE
Fanzy Zones install on ubuntu 24.04 does not work

### ISSUE THREAD

**Issue by JohnyRicio** [domferr/Linux-PowerToys#14]
When I try to install fancy zones than this error is returned.
Looks like that some prerequisities missing in doc or in app install process.
Ubuntu 24.04.1 LTS
Linux 6.8.0-41-generic
Gnome version 46

```bash
A Dart VM Service on Linux is available at: http://127.0.0.1:35795/0JCyldzBfdY=/
The Flutter DevTools debugger and profiler on Linux is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:35795/0JCyldzBfdY=/
flutter: [FINEST] 2024-09-09 06:15:05.278886: build() _FancyZonesScreenState
flutter: [FINEST] 2024-09-09 06:15:05.325942: build() _ActivationShortcut
flutter: [FINEST] 2024-09-09 06:15:05.330457: build() _EnableSnapAssistant
flutter: [FINEST] 2024-09-09 06:15:05.335670: build() _SpanMultipleZones
flutter: [FINEST] 2024-09-09 06:15:05.341485: build() _InnerGapsState
flutter: [FINEST] 2024-09-09 06:15:05.357990: build() _OuterGapsState
flutter: [FINEST] 2024-09-09 06:15:05.361951: build() LayoutSelection
flutter: [FINEST] 2024-09-09 06:15:05.369163: build() _Layout of Layout the id
flutter: [FINEST] 2024-09-09 06:15:05.374504: build() _SelectableLayout
flutter: [FINEST] 2024-09-09 06:15:05.377201: build() _SelectableLayout
flutter: [FINEST] 2024-09-09 06:15:05.377772: build() _SelectableLayout
flutter: [FINEST] 2024-09-09 06:15:05.378256: build() _SelectableLayout
flutter: [FINEST] 2024-09-09 06:15:05.378774: build() _SelectableLayout
flutter: [FINEST] 2024-09-09 06:15:05.379633: build() _NewLayoutButton
flutter: [SEVERE] 2024-09-09 06:15:05.435463: Failed to get 'inner-gaps' setting
flutter: [SEVERE] 2024-09-09 06:15:05.435842: Failed to get 'outer-gaps' setting
flutter: [SEVERE] 2024-09-09 06:15:05.436024: Failed to get 'enable-span-multiple-tiles' setting
flutter: [SEVERE] 2024-09-09 06:15:05.436183: Failed to get 'layouts-json' setting
flutter: [SEVERE] 2024-09-09 06:15:05.436395: Failed to get 'layouts-json' setting
flutter: [SEVERE] 2024-09-09 06:15:05.436575: Failed to get 'enable-snap-assist' setting
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: GSettings schema org.gnome.shell.extensions.modernwindowmanager not installed
#0      GSettings._load (package:gsettings/src/gsettings.dart:192:5)
<asynchronous suspension>
#1      new GSettings.<anonymous closure>.<anonymous closure> (package:gsettings/src/gsettings.dart:98:20)
<asynchronous suspension>

flutter: [FINEST] 2024-09-09 06:15:05.450967: build() _FancyZonesScreenState

```

**Comment by Goutam-Kelam** [comment]
@JohnyRicio I couldn’t replicate the issue exactly, but I did manage to get the package installed on Ubuntu 24.04 after some trial and error (and a little sulking). Here’s the adventure I embarked on:

1. I followed the README instructions to install Flutter and Dart, only to be greeted with this lovely error message:

   ```bash
   make run-debug
   flutter run -d linux
   # The current Dart SDK version is 2.18.4.
   # Because linuxpowertoys requires SDK version >=3.0.5 <4.0.0, version solving failed.
   ```

2. I figured, “Hey, let’s check the Dart version.” So I did:

   ```bash
   dart --version
   # Dart SDK version: 3.5.3 (stable)
   ```

   Great! My version was higher than 3.0.5, but apparently, that wasn’t enough for it to play nice. So, here’s what I did next:

   ```bash
   sudo apt update
   sudo apt upgrade
   sudo apt install curl git unzip xz-utils libglu1-mesa clang cmake ninja-build pkg-config libgtk-3-dev
   ```

3. Downloaded Flutter (because what’s better than another download, right?):

   ```bash
   cd ~
   curl -O https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.3.8-stable.tar.xz
   tar xf flutter_linux_3.3.8-stable.tar.xz
   echo 'export PATH="$PATH:$HOME/flutter/bin"' >> ~/.bashrc
   source ~/.bashrc
   ```

4. Rechecked Dart version (yes, I know, again):

   ```bash
   flutter channel stable
   flutter upgrade
   dart --version
   ```

5. Cloned the repo and *finally* gave it another go:

   ```bash
   git clone git@github.com:domferr/Linux-PowerToys.git
   cd Linux-PowerToys/
   make run-debug
   ```

6. Then I followed the instructions to install FancyZones, as a final act of faith.

And that’s how I got it up and running!
